const state = { mode: 'agent', busy: false, history: [] };
const byId = (id) => document.getElementById(id);
const chatLog = byId('chat-log');
const traceList = byId('trace-list');
const queryInput = byId('query');
const sendButton = byId('send-button');

function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[char])); }
function statusText(data) { return data.live_api ? `LIVE API · ${data.provider} · ${data.model}` : `MOCK FALLBACK · ${data.model}`; }
function setRuntime(data) { const node = byId('runtime-status'); node.textContent = statusText(data); node.className = `runtime ${data.live_api ? 'live' : 'mock'}`; }
function appendMessage(label, content, kind = 'agent', copyable = false) { const node = byId('message-template').content.firstElementChild.cloneNode(true); node.classList.add(kind); node.querySelector('.message-label').textContent = label; node.querySelector('.message-content').textContent = content; const copy = node.querySelector('.copy-button'); if (!copyable) copy.remove(); else copy.addEventListener('click', async () => { await navigator.clipboard.writeText(content); copy.textContent = 'Đã sao chép'; setTimeout(() => copy.textContent = 'Sao chép câu trả lời', 1300); }); byId('empty-state')?.remove(); chatLog.append(node); chatLog.scrollTop = chatLog.scrollHeight; }
function eventKind(event) { if (event.action_type === 'ERROR') return 'error'; if (event.action_type === 'FINAL_ANSWER') return 'final'; return 'loop'; }
function phase(title, content, kind) { return `<div class="react-phase ${kind}"><strong>${title}</strong><p>${escapeHtml(content || 'Không có nội dung')}</p></div>`; }
function eventMeta(event, data) { const status = event.observation?.status || ''; return `<div class="event-meta"><span class="chip">${escapeHtml(event.llm_provider || data.provider)}</span><span class="chip">${event.live_api ? 'LIVE API' : 'MOCK'}</span><span class="chip">${escapeHtml(String(event.latency_ms ?? 0))} ms</span>${status ? `<span class="chip">${escapeHtml(status)}</span>` : ''}</div>`; }
function renderTrace(trace, data) { traceList.innerHTML = ''; const loops = trace.filter(event => event.action_type === 'TOOL_EXECUTION').length; byId('trace-meta').textContent = `${loops} vòng ReAct${trace.some(event => event.action_type === 'FINAL_ANSWER') ? ' · Final Answer' : ''} · ${data.live_api ? 'LIVE API' : 'MOCK FALLBACK'}`; if (!trace.length) { traceList.innerHTML = '<div class="trace-empty">Chế độ Chatbot không gọi tool nên không có waterfall trace.</div>'; return; } trace.forEach((event, index) => { const type = eventKind(event); const raw = JSON.stringify(event, null, 2); const node = document.createElement('div'); node.className = `trace-event ${type}`; node.style.animationDelay = `${Math.min(index * 65, 260)}ms`; let phases = ''; if (event.action_type === 'TOOL_EXECUTION') { phases = `${phase('Thought', event.thought, 'thought')}${phase('Action', `${event.tool_name}(${JSON.stringify(event.arguments)})`, 'action')}${phase('Observation', JSON.stringify(event.observation || {}), 'observation')}`; } else if (event.action_type === 'FINAL_ANSWER') { phases = `${phase('Thought', event.thought, 'thought')}${phase('Final Answer', event.output, 'final-answer')}`; } else { phases = phase('Error', event.output, 'error-phase'); } const title = event.action_type === 'TOOL_EXECUTION' ? `Bước ${event.step} · ReAct Loop` : event.action_type === 'FINAL_ANSWER' ? `Bước ${event.step} · Hoàn tất` : `Bước ${event.step} · Error`; node.innerHTML = `<article><h3>${escapeHtml(title)}</h3><div class="react-phases">${phases}</div>${eventMeta(event, data)}<details><summary>View JSON</summary><pre>${escapeHtml(raw)}</pre></details></article>`; traceList.append(node); }); }
function setBusy(busy) { state.busy = busy; sendButton.disabled = busy; queryInput.disabled = busy; sendButton.textContent = busy ? 'Đang xử lý…' : 'Gửi câu hỏi'; }
async function sendQuery(query) { if (state.busy || !query.trim()) return; const userText = query.trim(); const priorHistory = state.history.slice(-12); appendMessage('BẠN', userText, 'user'); queryInput.value = ''; setBusy(true); try { const response = await fetch('/api/chat', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({query:userText, mode:state.mode, history:priorHistory}) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Không thể xử lý yêu cầu.'); setRuntime(data); appendMessage(state.mode === 'agent' ? 'VINHR REACT AGENT' : 'VINHR CHATBOT', data.answer, 'agent', true); state.history.push({role:'user', content:userText}, {role:'assistant', content:data.answer || ''}); state.history = state.history.slice(-12); renderTrace(data.trace, data); } catch (error) { appendMessage('LỖI', error.message || 'Không thể kết nối máy chủ.', 'agent'); renderTrace([{step:1, action_type:'ERROR', output:error.message || 'Lỗi kết nối', latency_ms:0}], {provider:'Web', live_api:false}); } finally { setBusy(false); queryInput.focus(); } }
async function loadSidebar() { const [examples, tools] = await Promise.all([fetch('/api/examples').then(r=>r.json()), fetch('/api/tools').then(r=>r.json())]); byId('scenario-count').textContent = examples.examples.length; const scenarios = byId('scenario-list'); examples.examples.forEach(item => { const button = document.createElement('button'); button.type = 'button'; button.className = 'scenario'; button.innerHTML = `<strong>${escapeHtml(item.title)}</strong><span>${item.tools === 0 ? '0 tool · trả lời trực tiếp' : `${item.tools} tool${item.tools > 1 ? 's' : ''} · ReAct`}</span>`; button.addEventListener('click', () => { state.mode = 'agent'; updateModeButtons(); queryInput.value = item.query; queryInput.focus(); }); scenarios.append(button); }); const toolList = byId('tool-list'); tools.tools.forEach(tool => { const node = document.createElement('div'); node.className = 'tool'; node.innerHTML = `<code>${escapeHtml(tool.name)}</code><p>${escapeHtml(tool.description)}</p>`; toolList.append(node); }); }
function updateModeButtons() { document.querySelectorAll('.mode-button').forEach(button => { const active = button.dataset.mode === state.mode; button.classList.toggle('active', active); button.setAttribute('aria-pressed', String(active)); }); }
byId('chat-form').addEventListener('submit', event => { event.preventDefault(); sendQuery(queryInput.value); }); queryInput.addEventListener('keydown', event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); byId('chat-form').requestSubmit(); } }); document.querySelectorAll('.mode-button').forEach(button => button.addEventListener('click', () => { state.mode = button.dataset.mode; updateModeButtons(); })); byId('clear-button').addEventListener('click', () => { state.history = []; chatLog.innerHTML = '<div class="empty-state" id="empty-state"><p class="empty-title">Sẵn sàng cho phiên demo</p><p>Chọn một kịch bản ở bên trái hoặc nhập câu hỏi HR.</p></div>'; traceList.innerHTML = '<div class="trace-empty">Thought, Action, Observation và Final Answer sẽ hiện ở đây.</div>'; byId('trace-meta').textContent = 'Chưa có lượt chạy'; queryInput.focus(); });
Promise.all([fetch('/api/status').then(r=>r.json()), loadSidebar()]).then(([data]) => setRuntime(data)).catch(() => { byId('runtime-status').textContent = 'Không kết nối được server'; });
